model_layers:
- positional_embedding
- text_projection
- logit_scale
- visual.class_embedding
- visual.positional_embedding
- visual.proj
- visual.conv1.weight
- visual.ln_pre.weight
- visual.ln_pre.bias
- visual.transformer.resblocks.0.attn.in_proj_weight
- visual.transformer.resblocks.0.attn.in_proj_bias
- visual.transformer.resblocks.0.attn.out_proj.weight
- visual.transformer.resblocks.0.attn.out_proj.bias
- visual.transformer.resblocks.0.ln_1.weight
- visual.transformer.resblocks.0.ln_1.bias
- visual.transformer.resblocks.0.mlp.c_fc.weight
- visual.transformer.resblocks.0.mlp.c_fc.bias
- visual.transformer.resblocks.0.mlp.c_proj.weight
- visual.transformer.resblocks.0.mlp.c_proj.bias
- visual.transformer.resblocks.0.ln_2.weight
- visual.transformer.resblocks.0.ln_2.bias
- visual.transformer.resblocks.1.attn.in_proj_weight
- visual.transformer.resblocks.1.attn.in_proj_bias
- visual.transformer.resblocks.1.attn.out_proj.weight
- visual.transformer.resblocks.1.attn.out_proj.bias
- visual.transformer.resblocks.1.ln_1.weight
- visual.transformer.resblocks.1.ln_1.bias
- visual.transformer.resblocks.1.mlp.c_fc.weight
- visual.transformer.resblocks.1.mlp.c_fc.bias
- visual.transformer.resblocks.1.mlp.c_proj.weight
- visual.transformer.resblocks.1.mlp.c_proj.bias
- visual.transformer.resblocks.1.ln_2.weight
- visual.transformer.resblocks.1.ln_2.bias
- visual.transformer.resblocks.2.attn.in_proj_weight
- visual.transformer.resblocks.2.attn.in_proj_bias
- visual.transformer.resblocks.2.attn.out_proj.weight
- visual.transformer.resblocks.2.attn.out_proj.bias
- visual.transformer.resblocks.2.ln_1.weight
- visual.transformer.resblocks.2.ln_1.bias
- visual.transformer.resblocks.2.mlp.c_fc.weight
- visual.transformer.resblocks.2.mlp.c_fc.bias
- visual.transformer.resblocks.2.mlp.c_proj.weight
- visual.transformer.resblocks.2.mlp.c_proj.bias
- visual.transformer.resblocks.2.ln_2.weight
- visual.transformer.resblocks.2.ln_2.bias
- visual.transformer.resblocks.3.attn.in_proj_weight
- visual.transformer.resblocks.3.attn.in_proj_bias
- visual.transformer.resblocks.3.attn.out_proj.weight
- visual.transformer.resblocks.3.attn.out_proj.bias
- visual.transformer.resblocks.3.ln_1.weight
- visual.transformer.resblocks.3.ln_1.bias
- visual.transformer.resblocks.3.mlp.c_fc.weight
- visual.transformer.resblocks.3.mlp.c_fc.bias
- visual.transformer.resblocks.3.mlp.c_proj.weight
- visual.transformer.resblocks.3.mlp.c_proj.bias
- visual.transformer.resblocks.3.ln_2.weight
- visual.transformer.resblocks.3.ln_2.bias
- visual.transformer.resblocks.4.attn.in_proj_weight
- visual.transformer.resblocks.4.attn.in_proj_bias
- visual.transformer.resblocks.4.attn.out_proj.weight
- visual.transformer.resblocks.4.attn.out_proj.bias
- visual.transformer.resblocks.4.ln_1.weight
- visual.transformer.resblocks.4.ln_1.bias
- visual.transformer.resblocks.4.mlp.c_fc.weight
- visual.transformer.resblocks.4.mlp.c_fc.bias
- visual.transformer.resblocks.4.mlp.c_proj.weight
- visual.transformer.resblocks.4.mlp.c_proj.bias
- visual.transformer.resblocks.4.ln_2.weight
- visual.transformer.resblocks.4.ln_2.bias
- visual.transformer.resblocks.5.attn.in_proj_weight
- visual.transformer.resblocks.5.attn.in_proj_bias
- visual.transformer.resblocks.5.attn.out_proj.weight
- visual.transformer.resblocks.5.attn.out_proj.bias
- visual.transformer.resblocks.5.ln_1.weight
- visual.transformer.resblocks.5.ln_1.bias
- visual.transformer.resblocks.5.mlp.c_fc.weight
- visual.transformer.resblocks.5.mlp.c_fc.bias
- visual.transformer.resblocks.5.mlp.c_proj.weight
- visual.transformer.resblocks.5.mlp.c_proj.bias
- visual.transformer.resblocks.5.ln_2.weight
- visual.transformer.resblocks.5.ln_2.bias
- visual.transformer.resblocks.6.attn.in_proj_weight
- visual.transformer.resblocks.6.attn.in_proj_bias
- visual.transformer.resblocks.6.attn.out_proj.weight
- visual.transformer.resblocks.6.attn.out_proj.bias
- visual.transformer.resblocks.6.ln_1.weight
- visual.transformer.resblocks.6.ln_1.bias
- visual.transformer.resblocks.6.mlp.c_fc.weight
- visual.transformer.resblocks.6.mlp.c_fc.bias
- visual.transformer.resblocks.6.mlp.c_proj.weight
- visual.transformer.resblocks.6.mlp.c_proj.bias
- visual.transformer.resblocks.6.ln_2.weight
- visual.transformer.resblocks.6.ln_2.bias
- visual.transformer.resblocks.7.attn.in_proj_weight
- visual.transformer.resblocks.7.attn.in_proj_bias
- visual.transformer.resblocks.7.attn.out_proj.weight
- visual.transformer.resblocks.7.attn.out_proj.bias
- visual.transformer.resblocks.7.ln_1.weight
- visual.transformer.resblocks.7.ln_1.bias
- visual.transformer.resblocks.7.mlp.c_fc.weight
- visual.transformer.resblocks.7.mlp.c_fc.bias
- visual.transformer.resblocks.7.mlp.c_proj.weight
- visual.transformer.resblocks.7.mlp.c_proj.bias
- visual.transformer.resblocks.7.ln_2.weight
- visual.transformer.resblocks.7.ln_2.bias
- visual.transformer.resblocks.8.attn.in_proj_weight
- visual.transformer.resblocks.8.attn.in_proj_bias
- visual.transformer.resblocks.8.attn.out_proj.weight
- visual.transformer.resblocks.8.attn.out_proj.bias
- visual.transformer.resblocks.8.ln_1.weight
- visual.transformer.resblocks.8.ln_1.bias
- visual.transformer.resblocks.8.mlp.c_fc.weight
- visual.transformer.resblocks.8.mlp.c_fc.bias
- visual.transformer.resblocks.8.mlp.c_proj.weight
- visual.transformer.resblocks.8.mlp.c_proj.bias
- visual.transformer.resblocks.8.ln_2.weight
- visual.transformer.resblocks.8.ln_2.bias
- visual.transformer.resblocks.9.attn.in_proj_weight
- visual.transformer.resblocks.9.attn.in_proj_bias
- visual.transformer.resblocks.9.attn.out_proj.weight
- visual.transformer.resblocks.9.attn.out_proj.bias
- visual.transformer.resblocks.9.ln_1.weight
- visual.transformer.resblocks.9.ln_1.bias
- visual.transformer.resblocks.9.mlp.c_fc.weight
- visual.transformer.resblocks.9.mlp.c_fc.bias
- visual.transformer.resblocks.9.mlp.c_proj.weight
- visual.transformer.resblocks.9.mlp.c_proj.bias
- visual.transformer.resblocks.9.ln_2.weight
- visual.transformer.resblocks.9.ln_2.bias
- visual.transformer.resblocks.10.attn.in_proj_weight
- visual.transformer.resblocks.10.attn.in_proj_bias
- visual.transformer.resblocks.10.attn.out_proj.weight
- visual.transformer.resblocks.10.attn.out_proj.bias
- visual.transformer.resblocks.10.ln_1.weight
- visual.transformer.resblocks.10.ln_1.bias
- visual.transformer.resblocks.10.mlp.c_fc.weight
- visual.transformer.resblocks.10.mlp.c_fc.bias
- visual.transformer.resblocks.10.mlp.c_proj.weight
- visual.transformer.resblocks.10.mlp.c_proj.bias
- visual.transformer.resblocks.10.ln_2.weight
- visual.transformer.resblocks.10.ln_2.bias
- visual.transformer.resblocks.11.attn.in_proj_weight
- visual.transformer.resblocks.11.attn.in_proj_bias
- visual.transformer.resblocks.11.attn.out_proj.weight
- visual.transformer.resblocks.11.attn.out_proj.bias
- visual.transformer.resblocks.11.ln_1.weight
- visual.transformer.resblocks.11.ln_1.bias
- visual.transformer.resblocks.11.mlp.c_fc.weight
- visual.transformer.resblocks.11.mlp.c_fc.bias
- visual.transformer.resblocks.11.mlp.c_proj.weight
- visual.transformer.resblocks.11.mlp.c_proj.bias
- visual.transformer.resblocks.11.ln_2.weight
- visual.transformer.resblocks.11.ln_2.bias
- visual.ln_post.weight
- visual.ln_post.bias
- transformer.resblocks.0.attn.in_proj_weight
- transformer.resblocks.0.attn.in_proj_bias
- transformer.resblocks.0.attn.out_proj.weight
- transformer.resblocks.0.attn.out_proj.bias
- transformer.resblocks.0.ln_1.weight
- transformer.resblocks.0.ln_1.bias
- transformer.resblocks.0.mlp.c_fc.weight
- transformer.resblocks.0.mlp.c_fc.bias
- transformer.resblocks.0.mlp.c_proj.weight
- transformer.resblocks.0.mlp.c_proj.bias
- transformer.resblocks.0.ln_2.weight
- transformer.resblocks.0.ln_2.bias
- transformer.resblocks.1.attn.in_proj_weight
- transformer.resblocks.1.attn.in_proj_bias
- transformer.resblocks.1.attn.out_proj.weight
- transformer.resblocks.1.attn.out_proj.bias
- transformer.resblocks.1.ln_1.weight
- transformer.resblocks.1.ln_1.bias
- transformer.resblocks.1.mlp.c_fc.weight
- transformer.resblocks.1.mlp.c_fc.bias
- transformer.resblocks.1.mlp.c_proj.weight
- transformer.resblocks.1.mlp.c_proj.bias
- transformer.resblocks.1.ln_2.weight
- transformer.resblocks.1.ln_2.bias
- transformer.resblocks.2.attn.in_proj_weight
- transformer.resblocks.2.attn.in_proj_bias
- transformer.resblocks.2.attn.out_proj.weight
- transformer.resblocks.2.attn.out_proj.bias
- transformer.resblocks.2.ln_1.weight
- transformer.resblocks.2.ln_1.bias
- transformer.resblocks.2.mlp.c_fc.weight
- transformer.resblocks.2.mlp.c_fc.bias
- transformer.resblocks.2.mlp.c_proj.weight
- transformer.resblocks.2.mlp.c_proj.bias
- transformer.resblocks.2.ln_2.weight
- transformer.resblocks.2.ln_2.bias
- transformer.resblocks.3.attn.in_proj_weight
- transformer.resblocks.3.attn.in_proj_bias
- transformer.resblocks.3.attn.out_proj.weight
- transformer.resblocks.3.attn.out_proj.bias
- transformer.resblocks.3.ln_1.weight
- transformer.resblocks.3.ln_1.bias
- transformer.resblocks.3.mlp.c_fc.weight
- transformer.resblocks.3.mlp.c_fc.bias
- transformer.resblocks.3.mlp.c_proj.weight
- transformer.resblocks.3.mlp.c_proj.bias
- transformer.resblocks.3.ln_2.weight
- transformer.resblocks.3.ln_2.bias
- transformer.resblocks.4.attn.in_proj_weight
- transformer.resblocks.4.attn.in_proj_bias
- transformer.resblocks.4.attn.out_proj.weight
- transformer.resblocks.4.attn.out_proj.bias
- transformer.resblocks.4.ln_1.weight
- transformer.resblocks.4.ln_1.bias
- transformer.resblocks.4.mlp.c_fc.weight
- transformer.resblocks.4.mlp.c_fc.bias
- transformer.resblocks.4.mlp.c_proj.weight
- transformer.resblocks.4.mlp.c_proj.bias
- transformer.resblocks.4.ln_2.weight
- transformer.resblocks.4.ln_2.bias
- transformer.resblocks.5.attn.in_proj_weight
- transformer.resblocks.5.attn.in_proj_bias
- transformer.resblocks.5.attn.out_proj.weight
- transformer.resblocks.5.attn.out_proj.bias
- transformer.resblocks.5.ln_1.weight
- transformer.resblocks.5.ln_1.bias
- transformer.resblocks.5.mlp.c_fc.weight
- transformer.resblocks.5.mlp.c_fc.bias
- transformer.resblocks.5.mlp.c_proj.weight
- transformer.resblocks.5.mlp.c_proj.bias
- transformer.resblocks.5.ln_2.weight
- transformer.resblocks.5.ln_2.bias
- transformer.resblocks.6.attn.in_proj_weight
- transformer.resblocks.6.attn.in_proj_bias
- transformer.resblocks.6.attn.out_proj.weight
- transformer.resblocks.6.attn.out_proj.bias
- transformer.resblocks.6.ln_1.weight
- transformer.resblocks.6.ln_1.bias
- transformer.resblocks.6.mlp.c_fc.weight
- transformer.resblocks.6.mlp.c_fc.bias
- transformer.resblocks.6.mlp.c_proj.weight
- transformer.resblocks.6.mlp.c_proj.bias
- transformer.resblocks.6.ln_2.weight
- transformer.resblocks.6.ln_2.bias
- transformer.resblocks.7.attn.in_proj_weight
- transformer.resblocks.7.attn.in_proj_bias
- transformer.resblocks.7.attn.out_proj.weight
- transformer.resblocks.7.attn.out_proj.bias
- transformer.resblocks.7.ln_1.weight
- transformer.resblocks.7.ln_1.bias
- transformer.resblocks.7.mlp.c_fc.weight
- transformer.resblocks.7.mlp.c_fc.bias
- transformer.resblocks.7.mlp.c_proj.weight
- transformer.resblocks.7.mlp.c_proj.bias
- transformer.resblocks.7.ln_2.weight
- transformer.resblocks.7.ln_2.bias
- transformer.resblocks.8.attn.in_proj_weight
- transformer.resblocks.8.attn.in_proj_bias
- transformer.resblocks.8.attn.out_proj.weight
- transformer.resblocks.8.attn.out_proj.bias
- transformer.resblocks.8.ln_1.weight
- transformer.resblocks.8.ln_1.bias
- transformer.resblocks.8.mlp.c_fc.weight
- transformer.resblocks.8.mlp.c_fc.bias
- transformer.resblocks.8.mlp.c_proj.weight
- transformer.resblocks.8.mlp.c_proj.bias
- transformer.resblocks.8.ln_2.weight
- transformer.resblocks.8.ln_2.bias
- transformer.resblocks.9.attn.in_proj_weight
- transformer.resblocks.9.attn.in_proj_bias
- transformer.resblocks.9.attn.out_proj.weight
- transformer.resblocks.9.attn.out_proj.bias
- transformer.resblocks.9.ln_1.weight
- transformer.resblocks.9.ln_1.bias
- transformer.resblocks.9.mlp.c_fc.weight
- transformer.resblocks.9.mlp.c_fc.bias
- transformer.resblocks.9.mlp.c_proj.weight
- transformer.resblocks.9.mlp.c_proj.bias
- transformer.resblocks.9.ln_2.weight
- transformer.resblocks.9.ln_2.bias
- transformer.resblocks.10.attn.in_proj_weight
- transformer.resblocks.10.attn.in_proj_bias
- transformer.resblocks.10.attn.out_proj.weight
- transformer.resblocks.10.attn.out_proj.bias
- transformer.resblocks.10.ln_1.weight
- transformer.resblocks.10.ln_1.bias
- transformer.resblocks.10.mlp.c_fc.weight
- transformer.resblocks.10.mlp.c_fc.bias
- transformer.resblocks.10.mlp.c_proj.weight
- transformer.resblocks.10.mlp.c_proj.bias
- transformer.resblocks.10.ln_2.weight
- transformer.resblocks.10.ln_2.bias
- transformer.resblocks.11.attn.in_proj_weight
- transformer.resblocks.11.attn.in_proj_bias
- transformer.resblocks.11.attn.out_proj.weight
- transformer.resblocks.11.attn.out_proj.bias
- transformer.resblocks.11.ln_1.weight
- transformer.resblocks.11.ln_1.bias
- transformer.resblocks.11.mlp.c_fc.weight
- transformer.resblocks.11.mlp.c_fc.bias
- transformer.resblocks.11.mlp.c_proj.weight
- transformer.resblocks.11.mlp.c_proj.bias
- transformer.resblocks.11.ln_2.weight
- transformer.resblocks.11.ln_2.bias
- token_embedding.weight
- ln_final.weight
- ln_final.bias
