data_parameters:
  file: "voxel_all.h5"
  DATA_READ_PATH: 'data/ScanObjectNN/processed_object_dataset/'
  prompt: "a volume data of a *"
  n_way: 10
  seed: 0
  batch_size: 80

model_parameters:
  model_name: "ViT-B/32" 
  train_layers:
  - visual.class_embedding
  - visual.positional_embedding
  - visual.conv1.weight
  - logit_scale
  train_whole_visual_layers:
  - logit_scale
  - visual.class_embedding
  - visual.positional_embedding
  - visual.proj
  - visual.conv1.weight
  - visual.ln_pre.weight
  - visual.ln_pre.bias
  - visual.transformer.resblocks.0.attn.in_proj_weight
  - visual.transformer.resblocks.0.attn.in_proj_bias
  - visual.transformer.resblocks.0.attn.out_proj.weight
  - visual.transformer.resblocks.0.attn.out_proj.bias
  - visual.transformer.resblocks.0.ln_1.weight
  - visual.transformer.resblocks.0.ln_1.bias
  - visual.transformer.resblocks.0.mlp.c_fc.weight
  - visual.transformer.resblocks.0.mlp.c_fc.bias
  - visual.transformer.resblocks.0.mlp.c_proj.weight
  - visual.transformer.resblocks.0.mlp.c_proj.bias
  - visual.transformer.resblocks.0.ln_2.weight
  - visual.transformer.resblocks.0.ln_2.bias
  - visual.transformer.resblocks.1.attn.in_proj_weight
  - visual.transformer.resblocks.1.attn.in_proj_bias
  - visual.transformer.resblocks.1.attn.out_proj.weight
  - visual.transformer.resblocks.1.attn.out_proj.bias
  - visual.transformer.resblocks.1.ln_1.weight
  - visual.transformer.resblocks.1.ln_1.bias
  - visual.transformer.resblocks.1.mlp.c_fc.weight
  - visual.transformer.resblocks.1.mlp.c_fc.bias
  - visual.transformer.resblocks.1.mlp.c_proj.weight
  - visual.transformer.resblocks.1.mlp.c_proj.bias
  - visual.transformer.resblocks.1.ln_2.weight
  - visual.transformer.resblocks.1.ln_2.bias
  - visual.transformer.resblocks.2.attn.in_proj_weight
  - visual.transformer.resblocks.2.attn.in_proj_bias
  - visual.transformer.resblocks.2.attn.out_proj.weight
  - visual.transformer.resblocks.2.attn.out_proj.bias
  - visual.transformer.resblocks.2.ln_1.weight
  - visual.transformer.resblocks.2.ln_1.bias
  - visual.transformer.resblocks.2.mlp.c_fc.weight
  - visual.transformer.resblocks.2.mlp.c_fc.bias
  - visual.transformer.resblocks.2.mlp.c_proj.weight
  - visual.transformer.resblocks.2.mlp.c_proj.bias
  - visual.transformer.resblocks.2.ln_2.weight
  - visual.transformer.resblocks.2.ln_2.bias
  - visual.transformer.resblocks.3.attn.in_proj_weight
  - visual.transformer.resblocks.3.attn.in_proj_bias
  - visual.transformer.resblocks.3.attn.out_proj.weight
  - visual.transformer.resblocks.3.attn.out_proj.bias
  - visual.transformer.resblocks.3.ln_1.weight
  - visual.transformer.resblocks.3.ln_1.bias
  - visual.transformer.resblocks.3.mlp.c_fc.weight
  - visual.transformer.resblocks.3.mlp.c_fc.bias
  - visual.transformer.resblocks.3.mlp.c_proj.weight
  - visual.transformer.resblocks.3.mlp.c_proj.bias
  - visual.transformer.resblocks.3.ln_2.weight
  - visual.transformer.resblocks.3.ln_2.bias
  - visual.transformer.resblocks.4.attn.in_proj_weight
  - visual.transformer.resblocks.4.attn.in_proj_bias
  - visual.transformer.resblocks.4.attn.out_proj.weight
  - visual.transformer.resblocks.4.attn.out_proj.bias
  - visual.transformer.resblocks.4.ln_1.weight
  - visual.transformer.resblocks.4.ln_1.bias
  - visual.transformer.resblocks.4.mlp.c_fc.weight
  - visual.transformer.resblocks.4.mlp.c_fc.bias
  - visual.transformer.resblocks.4.mlp.c_proj.weight
  - visual.transformer.resblocks.4.mlp.c_proj.bias
  - visual.transformer.resblocks.4.ln_2.weight
  - visual.transformer.resblocks.4.ln_2.bias
  - visual.transformer.resblocks.5.attn.in_proj_weight
  - visual.transformer.resblocks.5.attn.in_proj_bias
  - visual.transformer.resblocks.5.attn.out_proj.weight
  - visual.transformer.resblocks.5.attn.out_proj.bias
  - visual.transformer.resblocks.5.ln_1.weight
  - visual.transformer.resblocks.5.ln_1.bias
  - visual.transformer.resblocks.5.mlp.c_fc.weight
  - visual.transformer.resblocks.5.mlp.c_fc.bias
  - visual.transformer.resblocks.5.mlp.c_proj.weight
  - visual.transformer.resblocks.5.mlp.c_proj.bias
  - visual.transformer.resblocks.5.ln_2.weight
  - visual.transformer.resblocks.5.ln_2.bias
  - visual.transformer.resblocks.6.attn.in_proj_weight
  - visual.transformer.resblocks.6.attn.in_proj_bias
  - visual.transformer.resblocks.6.attn.out_proj.weight
  - visual.transformer.resblocks.6.attn.out_proj.bias
  - visual.transformer.resblocks.6.ln_1.weight
  - visual.transformer.resblocks.6.ln_1.bias
  - visual.transformer.resblocks.6.mlp.c_fc.weight
  - visual.transformer.resblocks.6.mlp.c_fc.bias
  - visual.transformer.resblocks.6.mlp.c_proj.weight
  - visual.transformer.resblocks.6.mlp.c_proj.bias
  - visual.transformer.resblocks.6.ln_2.weight
  - visual.transformer.resblocks.6.ln_2.bias
  - visual.transformer.resblocks.7.attn.in_proj_weight
  - visual.transformer.resblocks.7.attn.in_proj_bias
  - visual.transformer.resblocks.7.attn.out_proj.weight
  - visual.transformer.resblocks.7.attn.out_proj.bias
  - visual.transformer.resblocks.7.ln_1.weight
  - visual.transformer.resblocks.7.ln_1.bias
  - visual.transformer.resblocks.7.mlp.c_fc.weight
  - visual.transformer.resblocks.7.mlp.c_fc.bias
  - visual.transformer.resblocks.7.mlp.c_proj.weight
  - visual.transformer.resblocks.7.mlp.c_proj.bias
  - visual.transformer.resblocks.7.ln_2.weight
  - visual.transformer.resblocks.7.ln_2.bias
  - visual.transformer.resblocks.8.attn.in_proj_weight
  - visual.transformer.resblocks.8.attn.in_proj_bias
  - visual.transformer.resblocks.8.attn.out_proj.weight
  - visual.transformer.resblocks.8.attn.out_proj.bias
  - visual.transformer.resblocks.8.ln_1.weight
  - visual.transformer.resblocks.8.ln_1.bias
  - visual.transformer.resblocks.8.mlp.c_fc.weight
  - visual.transformer.resblocks.8.mlp.c_fc.bias
  - visual.transformer.resblocks.8.mlp.c_proj.weight
  - visual.transformer.resblocks.8.mlp.c_proj.bias
  - visual.transformer.resblocks.8.ln_2.weight
  - visual.transformer.resblocks.8.ln_2.bias
  - visual.transformer.resblocks.9.attn.in_proj_weight
  - visual.transformer.resblocks.9.attn.in_proj_bias
  - visual.transformer.resblocks.9.attn.out_proj.weight
  - visual.transformer.resblocks.9.attn.out_proj.bias
  - visual.transformer.resblocks.9.ln_1.weight
  - visual.transformer.resblocks.9.ln_1.bias
  - visual.transformer.resblocks.9.mlp.c_fc.weight
  - visual.transformer.resblocks.9.mlp.c_fc.bias
  - visual.transformer.resblocks.9.mlp.c_proj.weight
  - visual.transformer.resblocks.9.mlp.c_proj.bias
  - visual.transformer.resblocks.9.ln_2.weight
  - visual.transformer.resblocks.9.ln_2.bias
  - visual.transformer.resblocks.10.attn.in_proj_weight
  - visual.transformer.resblocks.10.attn.in_proj_bias
  - visual.transformer.resblocks.10.attn.out_proj.weight
  - visual.transformer.resblocks.10.attn.out_proj.bias
  - visual.transformer.resblocks.10.ln_1.weight
  - visual.transformer.resblocks.10.ln_1.bias
  - visual.transformer.resblocks.10.mlp.c_fc.weight
  - visual.transformer.resblocks.10.mlp.c_fc.bias
  - visual.transformer.resblocks.10.mlp.c_proj.weight
  - visual.transformer.resblocks.10.mlp.c_proj.bias
  - visual.transformer.resblocks.10.ln_2.weight
  - visual.transformer.resblocks.10.ln_2.bias
  - visual.transformer.resblocks.11.attn.in_proj_weight
  - visual.transformer.resblocks.11.attn.in_proj_bias
  - visual.transformer.resblocks.11.attn.out_proj.weight
  - visual.transformer.resblocks.11.attn.out_proj.bias
  - visual.transformer.resblocks.11.ln_1.weight
  - visual.transformer.resblocks.11.ln_1.bias
  - visual.transformer.resblocks.11.mlp.c_fc.weight
  - visual.transformer.resblocks.11.mlp.c_fc.bias
  - visual.transformer.resblocks.11.mlp.c_proj.weight
  - visual.transformer.resblocks.11.mlp.c_proj.bias
  - visual.transformer.resblocks.11.ln_2.weight
  - visual.transformer.resblocks.11.ln_2.bias
  - visual.ln_post.weight
  - visual.ln_post.bias
  num_epochs: 20
  log_interval: 5
  lr: 1e-5
  SAVE_MODEL_PATH: 'trained_model'
  # Adam optimizer is used with specific hyperparameters
  # lr (learning rate) is set to 5e-5, which is considered safe for fine-tuning to a new dataset
  # betas are used for the optimization algorithm
  # eps is a small value to prevent division by zero
  # weight_decay adds L2 regularization to the optimizer
  optimizer:
    betas: [0.9, 0.98]
    eps: 1e-6
    weight_decay: 0.2
    